### ISSUE TITLE
Estruturação do módulo data extractor

### ISSUE THREAD

**Issue by mathdesilva** [InstitutoTodosPelaSaude/monit-data-extractor#6]

**Comment by jaumpedro214** [comment]
Estruturação dos módulos básicos necessários para o correto funcionamento dos extratores:
- **Uploader** : Responsável pelo envio dos dados ao MinIO
- **Logger**   : Armazenar os logs de execução dos extratores para auditoria e investigação de problemas
- **Notifier**  : Notifica atrasos na extração _ex. Laboratório XYZ não envia dados pra o projeto Arbo há + de 7 dias._
