### ISSUE TITLE
Extração de dados do InfoDengue

### ISSUE THREAD

**Issue by mathdesilva** [InstitutoTodosPelaSaude/monit-data-extractor#8]

**Comment by jaumpedro214** [comment]
Arquivo com códigos exemplo de uso da API Info Dengue:

https://raw.githubusercontent.com/InstitutoTodosPelaSaude/arbo/bc89934bfb0478e236e326b31f3b979dfba68f0a/EDA/arbo_api_infodenv.ipynb

Referência Info Dengue:
https://info.dengue.mat.br/services/api
